language: ruby
rvm: 1.8.7
sudo: false

before_script:
# Create a database
# - "echo \"CREATE DATABASE chrono DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON chrono.* TO 'travis'@'localhost' IDENTIFIED BY 'chrono'; FLUSH PRIVILEGES;\" | mysql -u travis -p"
# Install dependencies
# - "sudo apt-get install graphicsmagick-libmagick-dev-compat imagemagick ri rdoc librmagick-ruby"
- "gem install rake -v 0.8.7"
- "gem install rdoc -v 2.3.0"
- "gem install json_pure -v 1.2.0"
- "gem install gchartrb -v 0.8"  
- "gem install RedCloth -v 4.2.2" 
- "gem install tzinfo -v 0.3.35" 
- "gem install echoe -v 4.1"
- "gem install fastercsv -v 1.5.5" 
- "gem install test-spec -v 0.10.0" 
- "gem install ferret -v 0.11.6" 
- "gem install hoe -v 2.5.0" 
- "gem install mongrel -v 1.1.5" 
- "gem install eventmachine -v 0.12.10"
- "gem install json -v 1.8.3"
- "gem install rmagick -v 2.12.2"
- "gem install ZenTest -v 4.1.4"
- "gem install icalendar -v 1.1.0"
- "gem install mysql -v 2.7"

script:
#  - "bundle exec rake ci:build"
- "ruby ./setup.rb  < ./test/setup.txt"
