language: ruby
rvm: 1.8.7
sudo: false

before_script:
# Install dependencies
# - "sudo apt-get install graphicsmagick-libmagick-dev-compat imagemagick ri rdoc librmagick-ruby"

# libmagick9-dev imagemagick ruby1.8 ruby1.8-dev rubygems ri rdoc rake
- "gem uninstall rake"
- "gem install rake -v 0.8.7"
- "gem install gchartrb RedCloth json tzinfo echoe fastercsv test-spec ferret hoe mongrel eventmachine"
- "gem install rmagick -v 2.12.2"
- "gem install ZenTest -v 4.1.4"
- "gem install icalendar -v 1.1.0"
- "gem install mysql -v 2.7"

#- "ruby ./setup.rb"
  
script:
#  - "bundle exec rake ci:build"
