language: ruby
rvm: 1.8.7
sudo: false

before_script:
# libmagick9-dev imagemagick ruby1.8 ruby1.8-dev rubygems ri rdoc rake
- "gem uninstall rake"
- "gem install rake -v 0.8.7"
- "gem install RedCloth"
- "gem install rake"
- "gem install ferret"
- "gem install fastercsv"
- "gem install eventmachine"
- "gem install rmagick"
- "gem install icalendar"
- "gem install mongrel"
- "gem install zentest"
- "gem install hoe"
- "gem install gchartrb"
- "gem install test-spec"
- "gem install echoe"
 


#- "ruby ./setup.rb"
  
script:
#  - "bundle exec rake ci:build"
